version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab2
    restart: unless-stopped
    hostname: gitlab.local
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.local';
        nginx['redirect_http_to_https'] = true;
        nginx['ssl_certificate'] = "/custom-ssl/gitlab.local.crt";
        nginx['ssl_certificate_key'] = "/custom-ssl/gitlab.local.key";
    ports:
      - "4443:443"
      - "4080:80"
      - "4022:22"
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
      - ./proxy/certbot/live/gitlab.local/fullchain.pem:/custom-ssl/gitlab.local.crt:ro
      - ./proxy/certbot/live/gitlab.local/privkey.pem:/custom-ssl/gitlab.local.key:ro